### PR TITLE
Custom red theme with 5th edition typography

### PR DESCRIPTION
**Pull request by ron-reaser**
I made some modifications to the 5th Edition SRD theme to make them stand out from the default mkdocs theme.

I recolored the Bootstrap theme with a stark red and gray color palette, evocative of the red brand logos for fifth edition. I replaced the default graph paper grid with a hex grid, more evocative of combat and miniatures. I defined font families for the body and text (sans-serif) and the headers (serif) so that the typography looks more like the content of fifth edition releases, using free likely-to-be-available alternatives with plenty of fallback options. I created a custom favicon using the site's colors and an iconic 5 in white on a red square backdrop. Finally, I upgraded FontAwesome to the latest version and minified all of the CSS files.

If you like the way the theme looks and want to use it on the main site, that would be pretty cool. If you think it needs work, let me know. And if you're not interested, I understand. Thanks for your time.

Oh, and now that I've forked the project, in the future if I find a typo or a formatting error I will try to fix it on my own and make a pull request instead of bothering you with an issue ticket.

### CODE REVIEW

**Comment by vitusventure** [comment]
This is totally awesome!  I love the design, and it definitely gives the site a unique look!  Thanks for putting in all the work on this, as you may have gathered from the current theme, I am not much of a web developer.  Merging this in now, and I will be doing a deployment in the next few days to get it published out.

**Comment by vitusventure** [comment]
I would like to give you credit on the main page for the new theme.  Just something along the lines of "New theme provided by <name>".  What would you like for the name there?  I can also make your name a link to your github, if you would like, or an email link.  Let me know what you would prefer.

**Comment by ron-reaser** [comment]
I'm excited that you decided to incorporate this. That's very cool. If you'd like to attribute me, just attribute me as Bloodcinder and link to my GitHub profile.  Thanks.

**Comment by vitusventure** [comment]
Bloodcinder,

Could you provide a bit of documentation as to how you compiled the css files with the .less file?  I wanted to experiment with adjusting the fonts, but when I try to compile the variables.less file with lessc, it complains about an undefined variable: 

`NameError: variable @ps-bg is undefined in /home/john/projects/5thSRD/5thsrd_theme/css/variables.less on line 14, column 11:
13 @brand-danger: rgb(217, 83, 79);
14 @body-bg: @ps-bg;
15 @text-color: @ps-text;`

What is the correct way to compile down the .less file?

**Comment by ron-reaser** [comment]
I actually used an online tool to generate the Boostrap CSS, and I exported the LESS variables so that they can be re-imported to that same tool if changes needed to be made.

I think the reason it complains about undefined variables is that they are ordered incorrectly. At least, I remember seeing that problem before.

What did you want to adjust about the fonts? I may be able to do it.

**Comment by vitusventure** [comment]
Ahh, that makes sense.

I noticed that with the current font stack, some pages are somewhat hard to read, especially where bolding is used to distinguish elements.  This can especially be observed [here](http://5thsrd.org/adventuring/equipment/adventuring_gear/) and in [monsters](http://5thsrd.org/gamemaster_rules/monsters/tarrasque/).

Changing the font stack in Chrome to something like: "Candara, Calibri, Segoe, Segoe UI, Optima, Arial, sans-serif", seems to make the page much more legible, while still keeping a look in the spirit of the official 5e documents.

Even once I get the paragraph's fixed, these specific places will still use the bolded text as distinguishing markers, so it will still make sense to change.

Let me know what you think, and thanks for your help with the site!

**Comment by ron-reaser** [comment]
To me, I think the font stack I have specified for sans-serif looks better, but that's just a side effect of personal preference, screen settings, and available fonts. I think as long as the serif fonts for the headers are still "antiquated" then the sans-serif fonts for the body can probably be anything.

My suggestion for the body would be `"Segoe", "Segoe UI", "Century Gothic", " CenturyGothic", "AppleGothic", "Optima", "Arial", sans-serif`

**Comment by vitusventure** [comment]
It is certainly very dependent on individual browsers and systems.  I currently test the site on my Macbook, iPhone, or Windows desktop.  

With your suggested stack above, it is still very easy for the eye to get lost in some sections, due to indistinct bolding.  [Ex1](http://i.imgur.com/lFPs1kz.png), [Ex2](http://i.imgur.com/giFykc4.png).

Perhaps something even more generic for the body would be best, so ensure that everything is readable for the large chunks of text.  Here are some comparison images with "Verdana, Geneva, sans-serif".

[Ex1](http://i.imgur.com/nYVkm7m.png)
[Ex2](http://i.imgur.com/RCoulFY.png)

A bit less exciting in the body, but putting the content first, since that is the core of the whole site.  I like the idea of keeping more interesting fonts in the header.

**Comment by ron-reaser** [comment]
Yeah, in your screenshots the bolding is very indistinct. It looks nothing like that on my system, but I guess that's due to the exact fonts that get used.

I'd say use your judgment here, since you have a wider variety of test environments you're using.

**Comment by vitusventure** [comment]
Fair enough.  Could you create a new PR with the "Verdana, Geneva, sans-serif" stack (or provide some instruction so I can regenerate the css), and I will build it to test and play around on some different environments?

**Comment by vitusventure** [comment]
Or, even better, could you rebuild with the current stack, but without the AppleGothic fallback?  That looks to be the weakly bolded font, and will keep it looking nice.

**Comment by vitusventure** [comment]
Pardon all the comments.  Since this would actually be a pretty minor change, I can just manually remove the problematic font from the two CSS files.

Again, I truly appreciate your work on this!

**Comment by ron-reaser** [comment]
That's all I would do anyway. Just find the offending AppleGothic font in bootstrap-custom.css and bootstrap-custom.min.css and carefully remove all instances.

**Pull request merged**
