### PR TITLE
Improve headers and paragraph spacing, fix issue #39

### PR DESCRIPTION
**Pull request by ron-reaser**

### CODE REVIEW

**Comment by ron-reaser** [comment]
Here's a preview of the style change.
screenshot-2017-11-17 magic items - 5th edition srd

**Comment by ron-reaser** [comment]
Do you know when you'll be rebuilding the site with these changes?

**Comment by vitusventure** [comment]
Soon, I had to rebuild my instance I was building on.

**Comment by vitusventure** [comment]
I built the site to the test stage, but it looks like the spacing between paragraphs doesn't match up to the sample you provided.  Here is the test stage: http://5thsrd.org-test.s3-website-us-east-1.amazonaws.com/adventuring/between_adventures/

Any idea why it isn't adding the extra spacing?  Some cursory examination in the console looks like the extra CSS rule is present...

**Comment by ron-reaser** [comment]
It is in my browser. What browser do you use? I may need to add some cross-browser fix.

**Comment by vitusventure** [comment]
Strange, was seeing no change in Chrome or Edge on Windows 10.

Must be an issue with my setup.  The site update is now done, so you should see changes after an hour or so as the edge caches refresh.

**Pull request merged**
